export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
export const POLLS_INFO_REQUEST = "POLLS_INFO_REQUEST";
export const POLLS_INFO_SUCCESS = "POLLS_INFO_SUCCESS";
export const POLLS_INFO_FAIL = "POLLS_INFO_FAIL";

export const POLLS_INFO_RESET = "POLLS_INFO_RESET";
export const ELECTION_INFO_REQUEST = "ELECTION_INFO_REQUEST";
export const ELECTION_INFO_SUCCESS = "ELECTION_INFO_SUCCESS";
export const ELECTION_INFO_FAIL = "ELECTION_INFO_FAIL";

export const ELECTION_INFO_RESET = "ELECTION_INFO_RESET";

export const SESSION_INFO_REQUEST = "SESSION_INFO_REQUEST";
export const SESSION_INFO_SUCCESS = "SESSION_INFO_SUCCESS";
export const SESSION_INFO_FAIL = "SESSION_INFO_FAIL";

export const SESSION_INFO_RESET = "SESSION_INFO_RESET";

export const ON_CHANGE_REQUEST = "ON_CHANGE_REQUEST";
export const ON_CHANGE_SUCCESS = "ON_CHANGE_SUCCESS";
export const ON_CHANGE_FAIL = "ON_CHANGE_FAIL";
export const ON_CHANGE_RESET = "ON_CHANGE_RESET";
export const CHANGE_YEAR = "CHANGE_YEAR";
